### ISSUE TITLE
Directory based subset

### ISSUE THREAD

**Issue by henryiii** [JBKahn/flake8-print#44]
Is there a way to select a directory? I really only care about prints in my package; in scripts, examples, and tests they are valid. I want to keep running the rest of flake8 on the other directories, though. I think I can make this work via pre-commit and splitting the check in two, but is there a better way? Thank you for this useful package!

**Comment by henryiii** [comment]
My problem was solved like this in pre-commit, but still wondering if there is a flake8 way to solve it:

```yaml
- repo: https://github.com/pycqa/flake8
  rev: 3.8.3
  hooks:
  - id: flake8
    exclude: docs/conf.py
    additional_dependencies: [flake8-bugbear]
  - id: flake8
    name: Print check
    files: src
    additional_dependencies: [flake8-print]
    args:
      - --select
      - T
```
