### ISSUE TITLE
Make flake8-print available as a pre-commit hook?

### ISSUE THREAD

**Issue by spenserblack** [JBKahn/flake8-print#58]
We've frequently had to catch `print` statements in PRs that should use loggers, and this seems like exactly the tool we need! :smiley:

However, would it be possible to make this available as a pre-commit hook ([docs](https://pre-commit.com/index.html#creating-new-hooks))? We would want to catch `print` statements before the commit is created, even if the developer forgets to run `flake8` locally.

**Comment by calumy** [comment]
Flake8-print can be run as part of the flake8 pre-commit hook. Hopefully, adding something like the following to your `.pre-commit-config.yaml` will work. 

```
  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-print
        args: [--config, setup.cfg]
```

Another option would be to add flake8 and flake8-print to your CI so that you will get a warning if there are print statements present in a PR.
